### ISSUE TITLE
ditto fails during "install_product" when building Catalina 10.15.4 with "No space left on device"

### ISSUE THREAD

**Issue by Wagonfixin** [grahampugh/macadmin-scripts#15]
Sadly, ditto fails during "install_product" when building Catalina 10.15.4 with "No space left on device".

`Making empty sparseimage...
installer: Package name is macOS Catalina
installer: Installing at base path /private/tmp/dmg.0eWnff
installer: The install was successful.
*********************************************************
*** Working around a very dumb Apple bug in a package ***
*** postinstall script that fails to correctly target ***
*** the Install macOS.app when installed to a volume  ***
*** other than the current boot volume.               ***
***       Please file feedback with Apple!            ***
*********************************************************
ditto: /private/tmp/dmg.0eWnff/Applications/Install macOS Catalina.app/Contents/SharedSupport/BaseSystem.dmg: No space left on device
Traceback (most recent call last):
  File "/Users/luser/bin/installinstallmacos.py", line 891, in <module>
    main()
  File "/Users/luser/bin/installinstallmacos.py", line 858, in main
    mountpoint)
  File "/Users/luser/bin/installinstallmacos.py", line 292, in install_product
    os.path.join(target_vol, 'Applications')]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[u'/usr/bin/ditto', u'/private/tmp/dmg.0eWnffApplications', u'/private/tmp/dmg.0eWnff/Applications']' returned non-zero exit status 1
`

Bails leaving dmg mounted and folder/file(s) in tmp…

**Comment by grahampugh** [comment]
I have fixed this by increasing the size of the disk image created to 10g instead of 8g.
