### ISSUE TITLE
error message and script fail - remotectl on non T2 mac

### ISSUE THREAD

**Issue by tao54tao** [grahampugh/macadmin-scripts#21]
Running script through the erase-install tool.  Has worked fine until today.  Errors on a non T2 macbook and imac.  Error message below:

```
Traceback (most recent call last):
  File "/Library/Management/erase-install/installinstallmacos.py", line 1184, in <module>
    main()
  File "/Library/Management/erase-install/installinstallmacos.py", line 778, in main
    bridge_id = get_bridge_id()
  File "/Library/Management/erase-install/installinstallmacos.py", line 115, in get_bridge_id
    raise ReplicationError(err)
__main__.ReplicationError: Command '[u'/usr/libexec/remotectl', u'get-property', u'localbridge', u'HWModel']' returned non-zero exit status 65
```

**Comment by grahampugh** [comment]
Ok, should be an easy fix. Weirdly I only had T1 devices to try this on. I'll take a quick look.

**Comment by grahampugh** [comment]
Please try again (might need to delete your `/Library/Management/erase-install` folder, although it should download afresh). I think I have now accounted for devices with no DeviceID.

**Comment by tao54tao** [comment]
All good now!  Thank you for the quick fix.
