### ISSUE TITLE
"content resides on a read-only file system."

### ISSUE THREAD

**Issue by monodata** [grahampugh/macadmin-scripts#23]
Tried moving the script to /Users/Shared (as suggested [here](https://github.com/munki/macadmin-scripts/blob/main/README.md#important-note-for-catalina): ) and changed perms to 777 but still get this error:

```
./content resides on a read-only file system.
Could not replicate https://swscan.apple.com/content/catalogs/others/index-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog: Command '[u'/usr/bin/curl', u'-sfL', u'--create-dirs', u'-o', u'./content/catalogs/others/index-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog', u'https://swscan.apple.com/content/catalogs/others/index-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog']' returned non-zero exit status 23
```

OS Version       : 10.15.6
Build ID         : 19G2021

**Comment by grahampugh** [comment]
`./content resides on a read-only file system.`
Can you investigate that further? I don't know what your system looks like.

I normally run the script in `/Library/Management/erase-install` and I don't get those errors.

**Comment by monodata** [comment]
I moved the script to /Users/Shared but got the same. My enterprise uses McAfee suite and I find the client proxy module causes no end of issues (especially with App Store) and once that was removed, it seems to work ok now.

Will need to speak with the guys that managed it as it should have excluded all the 17.x.x.x IP range from SSL inspection.
