### ISSUE TITLE
OS not downloading 

### ISSUE THREAD

**Issue by mani2care** [grahampugh/macadmin-scripts#32]
issue persists the same after the new version is not moving forward.

Script result:
[erase-install] v0.6.1 script execution started: Fri Dec 11 17:40:15 IST 2020
[erase-install] Caffeinating this script (pid=49514)
[erase-install] Looking for existing installer
[find_existing_installer] No valid installer found.
[erase-install] Starting download process
[erase-install] Opening jamfHelper download message (language=en)
[get_installinstallmacos] installinstallmacos.py is in /Library/Management/erase-install
[run_installinstallmacos] Checking that selected build 19H15 is available

[run_installinstallmacos] This command is now being run:

installinstallmacos.py --workdir=/Library/Management/erase-install --ignore-cache --raw --build=19H15 --validate
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed

0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
100 1976 100 1976 0 0 21617 0 --:--:-- --:--:-- --:--:-- 21714
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed

0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
0 475M 0 395k 0 0 603k 0 0:13:27 --:--:-- 0:13:27 603k
0 475M 0 1320k 0 0 796k 0 0:10:11 0:00:01 0:10:10 796k
0 475M 0 2489k 0 0 937k 0 0:08:39 0:00:02 0:08:37 937k
0 475M 0 3989k 0 0 1083k 0 0:07:29 0:00:03 0:07:26 1083k
1 475M 1 5557k 0 0 1193k 0 0:06:47 0:00:04 0:06:43 1193k
1 475M 1 7046k 0 0 1245k 0 0:06:30 0:00:05 0:06:25 1330k

39 7379M 39 2951M 0 0 930k 0 2:15:19 0:54:07 1:21:12 0
39 7379M 39 2951M 0 0 930k 0 2:15:22 0:54:08 1:21:14 0
39 7379M 39 2951M 0 0 930k 0 2:15:24 0:54:09 1:21:15 0
39 7379M 39 2951M 0 0 929k 0 2:15:26 0:54:09 1:21:17 0
curl: (56) Recv failure: Connection reset by peer
Could not replicate http://swcdn.apple.com/content/downloads/26/37/001-68446/r1dbqtmf3mtpikjnd04cq31p4jk91dceh8/InstallESDDmg.pkg: Command '[u'/usr/bin/curl', u'-fL', u'--create-dirs', u'-o', u'/Library/Management/erase-install/content/downloads/26/37/001-68446/r1dbqtmf3mtpikjnd04cq31p4jk91dceh8/InstallESDDmg.pkg', u'--compressed', 'http://swcdn.apple.com/content/downloads/26/37/001-68446/r1dbqtmf3mtpikjnd04cq31p4jk91dceh8/InstallESDDmg.pkg']' returned non-zero exit status 56

installinstallmacos.py - get macOS installers from the Apple software catalog

This Mac:
Model Identifier : MacBookPro14,1

Bridge ID : None
Board ID : Mac-B4831CEBD52A0C4C
OS Version : 10.13.6
Build ID : 17G11023
ProductID Version Build Post Date Title

1 001-68446 10.15.7 19H15 2020-11-11 macOS Catalina

Build 19H15 available. Downloading #1...

[run_installinstallmacos] Error obtaining valid installer. Cannot continue.
[erase-install] 'jamfHelper' ended

**Comment by grahampugh** [comment]
Duplicate issue from erase-install.
