### ISSUE TITLE
NO New Updates Anymore!

### ISSUE THREAD

**Issue by gcpmusic** [grahampugh/macadmin-scripts#33]
Hi, I have run for a while the script with no issue, both on Mojave and Big Sur. Downloaded and installed a few OS perfectly. Thank you.

However, lately seem to be stack showing always the some built and no new release. I have update Big Sur to 11.2 b2 showed via System Preferences but not from the script which is stack to 11.1.

I did tried to run the script with the --ignore-cache flag but didnt solved the issue.

Any help would be greatly appreciated.
Thank you in advance.
gC

**Comment by grahampugh** [comment]
I assume you are using the --seedprogram argument to list betas?

But anyway, unless I missed something, I don't think Apple have made full installers for 11.2 betas available, so 11.1 would be the latest full release available to you.

**Comment by gcpmusic** [comment]
Yes that correct. Many thanks for the reply and glad the script still working fine then :--)

All the best
gC
