### ISSUE TITLE
installinstallmacos.py not creating sparse image

### ISSUE THREAD

**Issue by Dragao75** [grahampugh/macadmin-scripts#34]
Hi I am running this script in order to get a sparse image but I get an error.

I am using a MacBook Pro Retina 13 inch early 2015 (MacBookPro12,1) running 10.15.7
I am running it like this: python /path/to/installinstallmacos.py --clear --ignore-cache --os=10.15 --raw 

The error I get is:
Making empty sparseimage...
installer: Error - the package path specified was invalid: './content/downloads/26/37/001-68446/r1dbqtmf3mtpikjnd04cq31p4jk91dceh8/001-68446.English.dist'.
Command '[u'/usr/sbin/installer', u'-pkg', u'./content/downloads/26/37/001-68446/r1dbqtmf3mtpikjnd04cq31p4jk91dceh8/001-68446.English.dist', u'-target', '/private/tmp/dmg.ZtUJnr']' returned non-zero exit status 1
Product installation failed.

I also have tried using --os=11 but getting the same error. 

Am I doing something wrong here ? The mac is hardware ready for Catalina as well as Big Sur.

**Comment by durack1** [comment]
I'm getting a similar issue on an older MacBook Pro (10,2), using the latest version of `installinstallmacos.py` https://github.com/grahampugh/macadmin-scripts/commit/f6df69e84717d96c134f96bbede6a9eef9705299

```
trustym:Shared duro$ sudo ./installinstallmacos.py --clear --raw --ignore-cache --version 10.15.7

installinstallmacos.py - get macOS installers from the Apple software catalog

This Mac:
Model Identifier : MacBookPro10,2

Board ID         : Mac-AFD8A9D944EA4843
OS Version       : 10.15.7
Build ID         : 19H105

 #  ProductID       Version    Build    Post Date   Title                          
 1  001-15219       10.15.5    19F2200  2020-06-15  macOS Catalina                 
 2  001-68446       10.15.7    19H15    2020-11-11  macOS Catalina                 
 3  001-04366       10.15.4    19E2269  2020-05-04  macOS Catalina                 
 4  061-86291       10.15.3    19D2064  2020-03-23  macOS Catalina                 
 5  041-91758       10.13.6    17G66    2019-10-19  macOS High Sierra              
 6  001-57224       10.15.7    19H4     2020-10-27  macOS Catalina                 
 7  061-26589       10.14.6    18G103   2019-10-14  macOS Mojave                   
 8  001-51042       10.15.7    19H2     2020-09-24  macOS Catalina                 
 9  001-36735       10.15.6    19G2006  2020-08-06  macOS Catalina                 
10  001-86606       11.1       20C69    2020-12-14  macOS Big Sur                  
11  041-88800       10.14.4    18E2034  2019-10-23  macOS Mojave                   
12  041-90855       10.13.5    17F66a   2019-10-23  Install macOS High Sierra Beta 
13  061-26578       10.14.5    18F2059  2019-10-14  macOS Mojave                   
14  001-36801       10.15.6    19G2021  2020-08-12  macOS Catalina                 
Removing existing content from working directory '.'...


Build 19H15 selected. Downloading #2...

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10.2M  100 10.2M    0     0  2301k      0  0:00:04  0:00:04 --:--:-- 2342k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1860k  100 1860k    0     0  3690k      0 --:--:-- --:--:-- --:--:-- 3683k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  477M  100  477M    0     0  2940k      0  0:02:46  0:02:46 --:--:-- 8690k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  475M  100  475M    0     0  12.5M      0  0:00:37  0:00:37 --:--:-- 13.4M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   328  100   328    0     0   2981      0 --:--:-- --:--:-- --:--:--  2981
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1976  100  1976    0     0  30875      0 --:--:-- --:--:-- --:--:-- 30875
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 7379M  100 7379M    0     0  12.2M      0  0:10:02  0:10:02 --:--:-- 13.1M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  780k    0  780k    0     0   317k      0 --:--:--  0:00:02 --:--:--  317k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 25290  100 25290    0     0   161k      0 --:--:-- --:--:-- --:--:--  161k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3073k  100 3073k    0     0  8088k      0 --:--:-- --:--:-- --:--:-- 8067k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   412  100   412    0     0   8956      0 --:--:-- --:--:-- --:--:--  8956
Making empty sparseimage...
installer: Error - the package path specified was invalid: './content/downloads/26/37/001-68446/r1dbqtmf3mtpikjnd04cq31p4jk91dceh8/001-68446.English.dist'.
Command '[u'/usr/sbin/installer', u'-pkg', u'./content/downloads/26/37/001-68446/r1dbqtmf3mtpikjnd04cq31p4jk91dceh8/001-68446.English.dist', u'-target', '/private/tmp/dmg.IpyBiZ']' returned non-zero exit status 1
Product installation failed.
```

**Comment by Dragao75** [comment]
I found out that without --clear it does work.

**Comment by durack1** [comment]
@Dragao75 that also appears to have fixed my problem too

**Comment by rbugajewski** [comment]
I have the same issue, but running the following command unfortunately does not solve it:

`sudo ./installinstallmacos.py --raw --ignore-cache --version 11.2.1`

Any ideas what else I could try?

**Comment by grahampugh** [comment]
@rbugajewski You could manually deleting the `content` folder. Can you post the output to confirm it's really the same issue?

**Comment by rbugajewski** [comment]
@grahampugh Thanks for the hint! I’ve already found an alternative solution, so unfortunately I cannot test anymore if deleting the `content` folder would solve this issue in my case. I’m 100% positive that the error message was the same, though, hence I skipped pasting it to prevent polluting this thread.

**Comment by grahampugh** [comment]
OK. I can't really help further then :-)  

Just for the other users in this thread, there is no need to use both `--clear` and `--ignore-cache` together. I added `--clear` because `--ignore-cache` doesn't actually delete the contents of the `content` folder. `--clear` should delete that folder, so there is no cache to ignore. Maybe there is some race condition I should look at that means supplying both does the wrong thing, but in the meantime, do not supply both :)

**Comment by grahampugh** [comment]
Actually, @Dragao75, I noticed a potential problem with the way you are using this script:

```python /path/to/installinstallmacos.py --clear --ignore-cache --os=10.15 --raw```

You are not supplying a working directory. If you don't supply a working directory, it defaults to `.`, i.e. your current directory. Since you could be running this command from anywhere, `./content` may or may not be populated. I suspect in your case it is not.

Another thing to be careful of. Do not run installinstallmacos.py from anywhere in your User folder.

As written by Greg in the README:

> If you attempt to install an incompatible version of macOS, you'll see an error similar to the following:

```
Making empty sparseimage...
installer: Error - ERROR_B14B14D9B7
Command '['/usr/sbin/installer', '-pkg', './content/downloads/07/20/091-95774/awldiototubemmsbocipx0ic9lj2kcu0pt/091-95774.English.dist', '-target', '/private/tmp/dmg.Hf0PHy']' returned non-zero exit status 1
Product installation failed.
```

>Use a compatible Mac or select a different build compatible with your current hardware and try again. You may also have success running the script in a VM; the InstallationCheck script in versions of the macOS installer to date skips the checks (and returns success) when run on a VM.
>
> Important note for Catalina+
>
>Catalina privacy protections might interfere with the operation of this tool if you run it from ~/Desktop, ~/Documents, ~/Downloads or other directories protected in Catalina. Consider using /Users/Shared (or subdirectory) as the "working space" for this tool.

**Comment by Dragao75** [comment]
Just to clarify, 
I just the command with (and without) workin dir same results. (and not from within Users Home)
But like you said before don't use --clear & --ignore-cache :) 
Regards
