### ISSUE TITLE
updating an iMacPro with High Sierra: "can't install Mojave on a non-apfs-volume.."

### ISSUE THREAD

**Issue by Efflar** [grahampugh/macadmin-scripts#36]
mojave installer cannot run cause internal volume is not APFS.. its still high sierra on an internal HFS+-volume..
after we updated many machines to mojave this is probably the last one and now i get this error..
Normally the step of reformatting the drive to APFS was included in mojave-installer I thought..
I tried two different builds, mojave 10.14.4 and 10.14.6.. getting the same result..
Does it make sense to better use an older version of installinstall.py ?
thank u for any help..

**Comment by grahampugh** [comment]
No, it makes not sense to use a different version of installinstallmacos.py

I'm surprised your iMacPro is not already APFS, but there's nothing to stop you converting it manually beforehand:

Restart your Mac and press-hold Command + R to boot into recovery mode. Then, go to Disk Utility << click Edit << click Convert to APFS.

**Comment by Efflar** [comment]
ahh.. maybe the macOS10.13.6 combo-update should fix this issue, I will give that a try..

**Comment by Efflar** [comment]
ok that should be easy, I will try this.. thank u graham!
