### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by Tb3986** [grahampugh/macadmin-scripts#38]
Hello,
i downloaded latest big sur installer from your script but i get this error:

Command '[u'/usr/sbin/installer', u'-pkg', u'./content/downloads/12/32/071-14766-A_Q2H6ELXGVG/zx8saim8tei7fezrmvu4vuab80m0e8a5ll/071-14766.English.dist', u'-target', '/private/tmp/dmg.935Cdu']' returned non-zero exit status 1
Product installation failed.
Command '[u'/usr/sbin/installer', u'-pkg', u'./content/downloads/12/32/071-14766-A_Q2H6ELXGVG/zx8saim8tei7fezrmvu4vuab80m0e8a5ll/071-14766.English.dist', u'-target', '/private/tmp/dmg.935Cdu']' returned non-zero exit status 1
Product installation failed.

Is there any workaround?

**Comment by grahampugh** [comment]
I'd need to see what command you ran. Either you are just having apple download problems, or else you are running the script from ~/Downloads or ~/Desktop which can cause problems.

**Comment by Tb3986** [comment]
> I'd need to see what command you ran. Either you are just having apple download problems, or else you are running the script from ~/Downloads or ~/Desktop which can cause problems.

I copied the folder on desktop but i always get the same error:

These are the command:

administrator@MacBook-Pro-di-Administrator ~ % cd Desktop/
administrator@MacBook-Pro-di-Administrator Desktop % cd a/
administrator@MacBook-Pro-di-Administrator a % ls
Install_macOS_11.2.3-20D91.sparseimage	createbootvolfromautonbi.py
LICENSE.md				docs
README.md				installinstallmacos.py
content					make_firmwareupdater_pkg.sh
administrator@MacBook-Pro-di-Administrator a % sudo ./installinstallmacos.py
Password:

installinstallmacos.py - get macOS installers from the Apple software catalog

After download, i get this:

Making empty sparseimage...
installer: Package name is macOS Big Sur
installer: Installing at base path /private/tmp/dmg.IneFHi
installer: The install failed. (Installer ha incontrato un errore che ha impedito l'installazione. Contatta il produttore del software per ottenere assistenza. Si è verificato un errore durante l'esecuzione degli script dal pacchetto “InstallAssistant.pkg.”)
Command '[u'/usr/sbin/installer', u'-pkg', u'./content/downloads/12/32/071-14766-A_Q2H6ELXGVG/zx8saim8tei7fezrmvu4vuab80m0e8a5ll/071-14766.English.dist', u'-target', '/private/tmp/dmg.IneFHi']' returned non-zero exit status 1
Product installation failed.
administrator@MacBook-Pro-di-Administrator a % 

All these process are under virtual machine with vmware & ryzen. Could be this the problem?

I'm using big sur 11.2.1

**Comment by grahampugh** [comment]
Don't run it from the desktop. Copy it to /Users/Shared and run it from there.

**Comment by Tb3986** [comment]
> Don't run it from the desktop. Copy it to /Users/Shared and run it from there.

Perfect works.
Thank you very much!
