### ISSUE TITLE
Board ID on a VM listed incorrectly in output

### ISSUE THREAD

**Issue by grahampugh** [grahampugh/macadmin-scripts#4]
Shown as `Board ID: latform`. Some kind of parsing error.

**Comment by ChefAustin** [comment]
Offending line: https://github.com/grahampugh/macadmin-scripts/blob/1bfd0c71b7f298296cfc276cf8274d30433dde33/installinstallmacos.py#L63

**Comment by ChefAustin** [comment]
This can now be closed as fix in PR #6 has been merged.

**Comment by grahampugh** [comment]
Thanks @ChefAustin
