### ISSUE TITLE
After loading to USB device via Disk Utilities, MacBook Air does not detect USB device while in target boot mode

### ISSUE THREAD

**Issue by stevebroskey** [grahampugh/macadmin-scripts#52]
### Steps to produce
- Successfully ran `installinstallmacos.py`, created Catalina installer (latest version) on MacBook Air. 
  - No errors on termination of the script.  
- Used Disk Utilities and Restore to load produced .dmg file to USB device (16GB thumb drive).
- When booting by holding down option, the thumb drive is not recognized. 

### Notes/Troubleshooting
- Flags include boot and all files appear to be present. Is this user error?  
- The same MacBook Air was used to produced the files/drive that is trying to utilize the install, so that requirement should be satisfied. 
- This MacBook Air shows an install of High Sierra on a thumb drive produced by the official instructions. 
- This thumb drive (with Catalina currently loaded) had previously been used to install High Sierra, so the thumb drive shouldn't be the problem.

Are there any steps I can take to further test or produce debugging output to confirm the script ran successfully?

**Comment by grahampugh** [comment]
You should use the createosinstaller command to create the bootable USB drive. I'm sure google will find you the syntax.
